namespace:
  name: sebastianschueler

istio:
  revision: default

website:
  image: sebastart/sebastianschueler-website
  imageVersion: "latest"
  host: sebastianschueler.de
  wwwHost: www.sebastianschueler.de
  replicas: 2
  port: 80
  targetPort: 80
  version: "v1"
  
  # Image pull secrets (optional)
  # imagePullSecrets:
  #   - name: docker-container-registry
  
  # Resource limits and requests
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  
  # Health checks
  healthCheck:
    enabled: true
    
  # Auto scaling
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80