apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: website
  namespace: {{ .Values.namespace.name }}
spec:
  host: website
  subsets:
  - name: {{ .Values.website.version | default "v1" }}
    labels:
      version: {{ .Values.website.version | default "v1" }}
  trafficPolicy:
    tls:
      mode: DISABLE