{{- if .Values.website.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: website-hpa
  namespace: {{ .Values.namespace.name }}
  labels:
    app: website
    {{ include "sebastianschueler-website.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: website
  minReplicas: {{ .Values.website.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.website.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.website.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.website.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
{{- end }}