apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: {{ .Values.namespace.name }}
  labels:
    app: website
      {{ include "sebastianschueler-website.labels" . | nindent 4 }}
spec:
  selector:
    app: website
    {{ include "sebastianschueler-website.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.website.port }}
      targetPort: {{ .Values.website.targetPort }}