apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: website-vs
  namespace: {{ .Values.namespace.name }}
spec:
  hosts:
  - {{ .Values.website.host }}
  - {{ .Values.website.wwwHost }}
  gateways:
  - istio-system/ingress-gateway
  http:
  # Redirect www to non-www
  - match:
    - uri:
        prefix: "/"
      headers:
        host:
          exact: {{ .Values.website.wwwHost }}
    redirect:
      authority: {{ .Values.website.host }}
      redirectCode: 301
  # Main routing
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: website
        subset: {{ .Values.website.version | default "v1" }}
        port:
          number: {{ .Values.website.port }}